export type PageId =
  | 'home'
  | 'particulieren'
  | 'horeca'
  | 'dienst-keukenmessen'
  | 'dienst-japanse-messen'
  | 'dienst-chips-herstellen'
  | 'dienst-wel-niet'
  | 'werkwijze'
  | 'ophalen-bezorgen'
  | 'blogs'
  | 'over-ons'
  | 'faq'
  | 'contact'
  | 'algemene-voorwaarden'
  | 'privacy';
